development:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
